name: build

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [ [acms, aCMs], [shapes, RNAShapes], [pkiss, pKiss], [palikiss, pAliKiss],  [rapidshapes, RapidShapes] , [alishapes, RNAalishapes],  [knotinframe, Knotinframe], [cofold, RNAcofold], [hybrid, RNAhybrid] ]
    steps:
      - uses: actions/checkout@v4
      - name: update apt
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install flex bison make libboost-all-dev libgsl-dev python3 python3-pip python3-biopython
      - name: clone gapc
        run: git clone -b master https://github.com/jlab/gapc.git $GITHUB_WORKSPACE/../gapc
      - name: configure
        run: cd $GITHUB_WORKSPACE/../gapc && ./configure
      - name: make
        run: cd $GITHUB_WORKSPACE/../gapc && make -j 2
      - name: make install
        run: cd $GITHUB_WORKSPACE/../gapc && sudo make install

      - name: Create Tree
        run: |
          make build-${{ matrix.task[0] }} &&
          cd ${{ github.workspace }}/Misc/Applications/${{ matrix.task[1] }}
          mkdir -p .debpkg/usr/bin/
          if [ -e ${{ matrix.task[1] }} ]; then
            cp ${{ matrix.task[1] }} .debpkg/usr/bin
          fi
          cp x86_64-linux-gnu/* .debpkg/usr/bin
          mkdir -p .debpkg/DEBIAN
      - uses: jiro4989/build-deb-action@v3
        id: build_deb
        with:
          package: ${{ matrix.task[1] }}
          package_root: .debpkg
          maintainer: To Be Determined
          version: v0.0.1 # refs/tags/v*.*.*
          arch: 'amd64'
          depends: 'bellmansgapc (>= 2023.07.05), git, perl'
          desc: 'this is sample package.'
      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        id: create_release
        with:
          tag: v0.0.1
          allowUpdates: true
          draft: true
          prerelease: true
          artifacts: ${{ steps.build_deb.outputs.file_name }}
          #body: This is the Body of the Release, how shall we dynamically set this? 
        env:
          GITHUB_TOKEN: ${{ github.token }}
        continue-on-error: true
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: v0.0.1
          files: ${{ steps.build_deb.outputs.file_name }}
          # upload_url: ${{ steps.create_release.outputs.upload_url }}

