name: build

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create sample script
        id: create_script
        run: |
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/usr/lib/samplescript
          echo -e "echo sample" > .debpkg/usr/bin/samplescript
          chmod +x .debpkg/usr/bin/samplescript
          echo -e "a=1" > .debpkg/usr/lib/samplescript/samplescript.conf

          # create DEBIAN directory if you want to add other pre/post scripts
          mkdir -p .debpkg/DEBIAN
          echo -e "echo postinst" > .debpkg/DEBIAN/postinst
          chmod +x .debpkg/DEBIAN/postinst
      - uses: jiro4989/build-deb-action@v3
        id: build_deb
        with:
          package: samplescript
          package_root: .debpkg
          maintainer: your_name
          version: v0.0.1 # refs/tags/v*.*.*
          arch: 'amd64'
          depends: 'libc6 (>= 2.2.1), git'
          desc: 'this is sample package.'
      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        id: create_release
        with:
          tag: v0.0.1
          allowUpdates: true
          draft: true
          prerelease: true
          bodyFile: ${{ steps.build_deb.outputs.DEB_FILE }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        continue-on-error: true
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.build_deb.outputs.DEB_FILE }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}

